### ISSUE TITLE
Allow for multiple parents

### ISSUE THREAD

**Issue by amccarri** [Swinject/Swinject#106]
I have a layered app architecture that divides responsibilities across several frameworks.  At the root level is an framework that depends on underlying peer frameworks.  Each one of those has it's own DI container.  I would like to expose services defined in all the underlying containers to the overall app.  This is currently not possible without creating an unnecessary dependency between peer frameworks since the container hierarchy only allows a single parent.

It would be nice if I could register multiple parent containers.

**Comment by yoichitgy** [comment]
Thanks @amccarri for the nice idea. Regarding parent/child relationship of containers, I would like to implement #80 first. It looks we need a good idea for implementation not to conflict with #80.

**Comment by jakubvano** [comment]
@amccarri I have been going over issues relating to parent-child container relationships - What you are describing looks like perfect usecase for `AssemblyType`s and `Assembler` - instead of exposing `Container` from individual frameworks you could expose an `AssemblyType` for each and then combine them into a single `Assembler`.

Or am I missing something there?

**Comment by yoichitgy** [comment]
I've been thinking about this, and Assembler looks working in this case. Adding multiple parents has a kind of [diamond problem](https://en.wikipedia.org/wiki/Multiple_inheritance) like multiple super class inheritance in C++ or similar.

**Comment by yoichitgy** [comment]
Closing this issue as `wontfix`. Please feel free to reopen this issue if you have a strong reason and good implementation to add this feature.
