### ISSUE TITLE
Multithreading and ObjectScope.Graph

### ISSUE THREAD

**Issue by tkohout** [Swinject/Swinject#135]
I had a problem when I created two objects using `resolve(service:argument)` method from two different threads. These object are quite large and take about 60ms to create. It looked something like this:

```
//First thread
r.resolve(MyService.self, argument: DynamicArgument(id: 5) )

.
.
.

//Second thread
r.resolve(MyService.self, argument: DynamicArgument(id: 6) )

```

Sometimes I got as a response of the second call object with id  == 5. After some debugging it looks like, the default ObjectScope.Graph was used and Swinject used the first object from the resolution pool. When I change scope to .None everything works as expected.

This is quite unexpected behaviour and I am surprised it didn't come up before. Any chance for fixing it in future release?

Cheers
Tomas

**Comment by yoichitgy** [comment]
@tkohout, let me confirm one thing. You got the resolver (`r`) by `synchronize` method?

```swift
let resolver = container.synchronize()
```

Also, your example code is not in `register` method, isn't it?

**Comment by tkohout** [comment]
I see, I don't know how I missed the ThreadSafety documentation. 
`synchronize` solves it.

Thanks
Tomas

**Comment by yoichitgy** [comment]
That's ok😀

Just FYI: I'm planning to change thread safety API. The current implementation returning SynchronizedResolver is quite bad for maintenance. It looks passing a DispatchQueue to Container's initializer is better.

Another motivation is: previously I used OSSpinLock for performance, but it turned out OSSpinLock has a problem (#116). So using DispatchQueue in a container looks good. Container is thread-safe only if DispatchQueue queue is passed.

**Comment by yoichitgy** [comment]
The new thread safe model I'm planning is #139.
