### ISSUE TITLE
ObjectScope.Container object created multiple times

### ISSUE THREAD

**Issue by kl** [Swinject/Swinject#16]
I have the following code:

```swift
var container: Container {
  let container = Container()

  container.register(Networking.self) { _ in Network() }.inObjectScope(.Container)
  container.register(RestServicing.self) { r in
    RestService(networking: r.resolve(Networking.self)!, apiBase: "http://192.168.1.12:8080")
  }.inObjectScope(.Container)

  return container
}
```

then later on:

```swift
let restService = container.resolve(RestServicing.self) as! RestService
let restService2 = container.resolve(RestServicing.self) as! RestService
```

When I run this code and put a breakpoint on the line ```RestService(networking: r.resolve(Networking.self)!, apiBase: "http://192.168.1.12:8080").inObjectScope(.Container)``` it hits the breakpoint twice and two different RestService objects are created. I thought only one instance should be created?

**Comment by ikesyo** [comment]
The `container` property you defined is a computed property, so a fresh container instance will be created for each time.

**Comment by kl** [comment]
Yes, I just realised as I posted this! :sweat_smile: Sorry about that.

**Comment by yoichitgy** [comment]
Thank you, @ikesyo, for the prompt response!

**Comment by yoichitgy** [comment]
I think the example in [my blog](https://yoichitgy.github.io/post/dependency-injection-in-mvvm-architecture-with-reactivecocoa-part-4-implementing-the-view-and-viewmodel/) and [SwinjectMVVMExample](https://github.com/Swinject/SwinjectMVVMExample) was bad because it uses the computed property. I will fix the blog.

Probably (in the most of cases), a stored property defined as below is better.


    var container: Container = {
        let container = Container()
        
        // The container setup...

        return container
    }()

[This document](https://github.com/Swinject/Swinject/blob/master/Documentation/Storyboard.md) has an example of that kind of stored property in `AppDelegate`.
