### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by RLovelett** [Swinject/Swinject#21]
Are there any guides/guide lines on contributing? Specifically I was hoping to extend some features/syntax and I wanted to be able to add a test however it is non-obvious to me how I should execute the test suite in the first place. Are there any other pieces of information I should know before undertaking a pull-request?

**Comment by yoichitgy** [comment]
Thank you for asking. I was always thinking I should add a contribution guide [like Carthage has](https://github.com/Carthage/Carthage), a simple one.

Basically I follow [the Swift coding guidelines of GitHub](https://github.com/github/swift-style-guide).

To run unit tests on Xcode with `Command-U`, you need run Carthage first.

```
carthage bootstrap --no-use-binaries --use-submodules
```

For now, because it fails with a tvOS issue, platforms should be specified to workaround.

```
carthage bootstrap --no-use-binaries --use-submodules --platform iOS,Mac,watchOS
```

Travis can test tvOS target even for now, so your pull request will be tested for all the targets before it is merged.

**Comment by RLovelett** [comment]
Another piece of information is that it requires Carthage greater than 0.8.0 (not sure which is required). Just know I had 0.8.0 and had to go to 0.9.4 and now that command succeeds.

**Comment by yoichitgy** [comment]
Thanks for mentioning the version of Carthage. The latest version of Carthage is always preferable just because I do not test older versions. Currently Homebrew cannot install the latest version of Carthage. The installer of the latest version is available at the Carthage release page:

https://github.com/Carthage/Carthage/releases

0.9.4 is the latest at the moment.

**Comment by yoichitgy** [comment]
Added a contribution guide.

https://github.com/Swinject/Swinject/blob/master/CONTRIBUTING.md
