### ISSUE TITLE
Exception on registering simple service / component

### ISSUE THREAD

**Issue by benjamincombes** [Swinject/Swinject#4]
Hi,
I'm making tests to consider using Swinject in a new project (it looks great :) !) ; however, anytime I try to use it, I get a runtime exception.
I tried with a simple code to create a container and register service / component ; and when running the application, I had a runtime exception:
Exception: EXC_BREAKPOINT (code=1, subcode=0x120031088))
![capture d ecran 2015-09-24 a 13 30 44](https://cloud.githubusercontent.com/assets/138637/10072335/0c0e733a-62c1-11e5-9c41-bb52f014dc34.png)

In order to be sure the problem didn't come from my code, I simply copied your sample code, what resulted in the same exception on this part of code :
container.register(AnimalType.self) {
      _ in Cat(name: "Mimi")
}

I'm using Xcode 7.0 (7A220), OSX 10.11 (15A278b), and added Swinject via Carthage.
Do you have any idea of what might cause this, am I doing something wrong ?
Thanks a lot for your help.

**Comment by yoichitgy** [comment]
Thank you for using Swinject. Can you provide more code to reproduce the problem? Did you use Swinject version 0.2.1?

**Comment by benjamincombes** [comment]
Thanks for your fast answer!
I used version 0.2.1, using 'github "Swinject/Swinject" ~> 0.2' in my Cartfile.
Actually I tried again with an empty project to be sure it doesn't come from my project setup, but I get the same result, you can find it there: 
http://s000.tinyupload.com/index.php?file_id=04255268079753436693
Let me know if I can do anything to help reproduce the issue or get details about it, and thanks a lot for your help!

**Comment by yoichitgy** [comment]
You can solve the problem by running `carthage update` or `carthage bootstrap` commands with `--no-use-binaries` option.

`carthage update --no-use-binaries`

The cause of the problem was that a zipped framework built with Xcode 7 beta 5 was attached to the Swinject release version 0.2.1. I had misunderstanding that the built framework worked with official Xcode 7. I have to release version 0.2.2 with a zipped framework built with Xcode 7.

I really appreciate you posted the problem. Thank you!

**Comment by benjamincombes** [comment]
Thanks for the fast workaround, I just tried it and it works a lot better, I can start having some fun with Swinject now :) ! Glad it helped a little, and thanks again for your work!
