### ISSUE TITLE
view controller injection

### ISSUE THREAD

**Issue by marciliojrs** [Swinject/Swinject#7]
Hello guys, 

I'm registering one view controller using the method `registerForStoryboard` but when I get this controller using `resolve`, the return is nil.

```
container.registerForStoryboard(PostDetailVC.self) { (r, c) in
    c.presenter = r.resolve(PostDetailPresenter.self)
}

container.register(PostDetailWireframe.self) { (r) in
    let wireframe = PostDetailWireframe()

    wireframe.postDetailViewController = r.resolve(PostDetailVC.self)
    
    return wireframe
}
```

There's something wrong with this code? 

Thanks

**Comment by yoichitgy** [comment]
`registerForStoryboard` is used to inject dependency in the same way as [`initCompleted`](https://github.com/Swinject/Swinject/blob/master/Documentation/InjectionPatterns.md). You need register `PostDetailVC.self` by calling `container.register(PostDetailVC.self)`. In the registration closure, you will probably call `instantiateViewControllerWithIdentifier` on a storyboard.

The problem here is the naming of `registerForStoryboard` is confusing. I have to rename the method to tell it does only the same thing as `initCompleted` does.

**Comment by marciliojrs** [comment]
Thanks! I had tried this approach but I was facing some circular injection problems. I found the circular problem and this approach worked. Thanks a lot.
